insert into CustomerAddress (customer_id, address, city, postal_code, country) values (2, '8265 Summit Parkway', 'Mercedes', '3470', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (4, '7080 Veith Drive', 'Laboulaye', '5120', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (92, '3223 Lakeland Street', 'Chillán', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (23, '31 Sloan Avenue', 'El Soberbio', '3364', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (83, '073 Grover Avenue', 'Bandera', '3064', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (71, '3 Granby Street', 'Villa Cañás', '2607', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (36, '2317 Sundown Parkway', 'Firmat', '2630', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (3, '82 Truax Avenue', 'Tandil', '7000', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (28, '876 Springview Drive', 'Chimbas', '5413', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (88, '94983 Artisan Parkway', 'San Lorenzo', '2200', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (88, '1 Granby Plaza', 'Rojas', '5246', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (49, '05 Spohn Hill', 'La Laja', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (3, '35 Hazelcrest Crossing', 'Punta Alta', '8109', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (53, '51 Village Park', 'Valle Grande', '4513', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (40, '96 Dawn Way', 'La Playosa', '5911', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (6, '147 Del Mar Street', 'Quillota', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (49, '0 Hudson Circle', 'Libertador General San Martín', '5771', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (62, '12 Hooker Drive', 'Luján de Cuyo', '5544', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (83, '8424 Mccormick Terrace', 'Molinos', '4616', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (6, '8 Bobwhite Plaza', 'Colonia Wanda', '3376', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (45, '8574 Dorton Hill', 'Brea Pozo', '4313', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (12, '29 Dottie Trail', 'Rivadavia', '3081', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (14, '383 Magdeline Road', 'Garupá', '3304', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (34, '6 Reindahl Road', 'Monteros', '4142', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (37, '9 Stuart Point', 'Corral de Bustos', '2645', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (70, '321 Derek Crossing', 'Migues', null, 'Uruguay');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (46, '424 Manufacturers Alley', 'Treinta y Tres', null, 'Uruguay');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (4, '8 Grover Parkway', 'La Ensenada', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (66, '301 Mendota Plaza', 'Pérez', '2121', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (56, '5278 Lerdahl Drive', 'La Francia', '2426', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (51, '7368 Carpenter Parkway', 'General Galarza', '2843', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (54, '2 Northland Hill', 'Nueve de Julio', '3606', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (60, '082 Bonner Circle', 'Villa Ascasubi', '5935', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (38, '352 Waywood Parkway', 'Palpalá', '4612', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (69, '715 Hollow Ridge Crossing', 'Avellaneda', '5212', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (38, '719 Mccormick Junction', 'Lobos', '7240', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (32, '6 Dexter Pass', 'San Felipe', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (52, '60502 Messerschmidt Parkway', 'Rafael Perazza', null, 'Uruguay');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (67, '85702 Rockefeller Lane', 'Yuto', '4518', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (83, '5 Blackbird Circle', 'Lo Prado', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (9, '4455 Karstens Trail', 'Alderetes', '4178', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (84, '7644 Corscot Lane', 'Azul', '7300', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (91, '579 Evergreen Center', 'James Craik', '5984', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (26, '7914 Pawling Avenue', 'Valcheta', '8536', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (74, '2 Rockefeller Court', 'Las Heras', '9017', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (91, '9 Packers Drive', 'Achiras', '3246', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (16, '186 Donald Lane', 'Rafaela', '2300', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (30, '5181 Sauthoff Hill', 'Coronel', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (49, '100 Merchant Drive', 'Avellaneda', '5212', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (97, '0450 Forest Run Road', 'Chilecito', '3412', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (56, '4 Upham Lane', 'Tafí Viejo', '4105', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (82, '5548 Emmet Plaza', 'Penco', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (12, '8 Petterle Road', 'La Cesira', '5101', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (80, '3 Schiller Avenue', 'Cutral-Có', '8322', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (2, '3 Darwin Park', 'Villa Nueva', '5903', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (61, '1435 Acker Drive', 'Carhué', '6433', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (46, '111 Mandrake Park', 'Arias', '2624', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (46, '64 Arkansas Drive', 'Calbuco', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (63, '50484 Acker Court', 'Tres Isletas', '4000', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (5, '822 Eliot Place', 'Bella Vista', '9400', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (35, '6013 Coleman Place', 'Bahía Blanca', '8000', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (31, '09555 Corscot Park', 'Herrera', '4326', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (96, '19273 Surrey Trail', 'Apóstoles', '3358', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (37, '97 Lakewood Gardens Park', 'Ancasti', '4701', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (5, '198 Carioca Plaza', 'Rawson', '9103', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (73, '9 Rusk Alley', 'El Soberbio', '3364', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (35, '12368 Trailsway Lane', 'Santo Tomé', '5719', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (82, '236 Pennsylvania Circle', 'Lota', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (62, '60216 Kensington Drive', 'Coronel Belisle', '8364', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (77, '2 Longview Avenue', 'La Quiaca', '3461', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (19, '6824 Waubesa Crossing', 'Capitán Bermúdez', '2156', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (98, '65358 Almo Circle', 'Allen', '8328', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (51, '09 Merry Point', 'Unión', '2529', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (71, '00241 Burrows Drive', 'Santa Bernardina', null, 'Uruguay');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (4, '98 Morrow Street', 'Arias', '2624', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (87, '49 Dapin Way', 'Villa Gesell', '7165', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (98, '31 Forest Hill', 'Goya', '3450', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (50, '392 Arkansas Alley', 'Juan L. Lacaze', null, 'Uruguay');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (91, '0805 Farragut Circle', 'Chile Chico', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (33, '99002 Old Shore Pass', 'Chichinales', '8326', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (52, '3346 Moland Place', 'Luján', '6700', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (77, '8 Lakewood Center', 'Panguipulli', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (49, '662 Bartelt Plaza', 'Curanilahue', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (9, '01 Stephen Drive', 'Viña del Mar', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (13, '282 Hoepker Drive', 'Viña del Mar', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (49, '7 Carioca Pass', 'La Ligua', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (61, '9 Melrose Parkway', 'Inriville', '2587', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (73, '44163 Clyde Gallagher Center', 'Ceres', '2340', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (99, '53799 Ridgeview Avenue', 'Embalse', '5856', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (96, '6526 Morningstar Drive', 'Almafuerte', '3317', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (43, '04 Rusk Street', 'Cañete', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (13, '08 Melby Place', 'La Floresta', null, 'Uruguay');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (22, '325 Miller Park', 'Jesús María', '5223', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (98, '188 Mockingbird Terrace', 'Joaquín Suárez', null, 'Uruguay');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (58, '7 Shopko Point', 'Doblas', '6305', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (58, '0831 Butternut Hill', 'Lebu', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (24, '219 Westridge Pass', 'Río Cuarto', '6360', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (59, '7788 Dapin Parkway', 'Salamanca', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (55, '8548 Dexter Junction', 'Goya', '3450', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (75, '92 Drewry Terrace', 'San Felipe', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (29, '5068 Golden Leaf Avenue', 'Arraga', '4206', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (48, '18382 Elmside Trail', 'Palpalá', '4612', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (71, '2135 Calypso Crossing', 'Talagante', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (99, '51210 Brown Point', 'Río Colorado', '8138', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (66, '34186 Debs Trail', 'Zapala', '8340', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (52, '5438 Redwing Trail', 'Chichinales', '8326', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (55, '99 Browning Road', 'Posadas', '3300', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (27, '5 Twin Pines Park', 'Deán Funes', '4417', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (63, '494 Lakewood Gardens Pass', 'Alto Río Senguer', '9033', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (16, '42 Old Shore Hill', 'La Tigra', '5949', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (70, '52653 Riverside Park', 'Clodomira', '4338', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (43, '192 Huxley Lane', 'Villa Nueva', '5903', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (31, '10659 Bartillon Crossing', 'Chilecito', '3412', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (87, '41900 Esker Center', 'Santiago del Estero', '4200', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (58, '71 Scott Avenue', 'Concepción', '4149', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (3, '3936 Morrow Plaza', 'Buta Ranquil', '8353', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (13, '63 Laurel Junction', 'Punta Alta', '8109', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (70, '70597 Vernon Street', 'El Carril', '4421', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (1, '0591 Victoria Hill', 'Reconquista', '3560', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (98, '8800 Forest Plaza', 'Paso de los Libres', '3230', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (59, '09 Raven Road', 'Telsen', '9121', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (75, '52 Artisan Street', 'Malvinas Argentinas', '5125', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (29, '1430 Pearson Circle', 'Daireaux', '6555', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (43, '0 Sheridan Crossing', 'Chajarí', '3228', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (19, '0 Gerald Circle', 'Elena', '5815', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (22, '3219 Novick Place', 'Limache', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (62, '2118 Victoria Alley', 'Villa Ojo de Agua', '5250', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (73, '854 Commercial Drive', 'Young', null, 'Uruguay');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (33, '9555 Packers Parkway', 'Peñaflor', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (39, '0 Dayton Trail', 'Villa Cañás', '2607', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (84, '8 Mcguire Hill', 'Corral', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (74, '267 Chive Lane', 'General Belgrano', '7223', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (17, '928 Toban Road', 'Huanchillas', '6121', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (22, '95910 Pepper Wood Place', 'San Antonio Oeste', '8520', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (68, '92386 Caliangt Park', 'Cachí', '4417', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (53, '30261 Darwin Center', 'Taltal', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (85, '84190 Badeau Court', 'Libertad', '3374', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (46, '83896 Loeprich Crossing', 'San Antonio', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (76, '01 Mcbride Parkway', 'Villa Las Rosas', '5875', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (50, '552 Lukken Crossing', 'Rancagua', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (92, '48635 Vidon Way', 'Melipilla', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (77, '0 Dwight Street', 'San Luis del Palmar', '3403', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (34, '178 Surrey Crossing', 'Barra de Carrasco', null, 'Uruguay');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (95, '00961 David Hill', 'Vera', '3550', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (1, '9867 Del Mar Pass', 'Villa Alemana', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (80, '51211 Mitchell Lane', 'Albardón', '5419', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (16, '2711 Mayer Avenue', 'La Cocha', '4162', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (93, '231 John Wall Trail', 'General Alvear', '3361', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (53, '0860 Packers Pass', 'La Cumbre', '6354', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (71, '6125 Westerfield Parkway', 'Cañada de Gómez', '2500', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (37, '00 Burning Wood Trail', 'Comallo', '8416', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (74, '056 Montana Trail', 'Puan', '8180', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (66, '1146 Carpenter Pass', 'San Vicente', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (99, '2257 Dawn Parkway', 'Villa Castelli', '5355', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (77, '22318 Butterfield Alley', 'Carcarañá', '2138', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (27, '21628 Hazelcrest Drive', 'Unquillo', '5109', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (58, '42045 Brown Avenue', 'Colón', '3280', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (32, '3390 Springview Parkway', 'Victoria', '3153', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (6, '8298 Caliangt Street', 'Capayán', '4726', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (87, '2910 Transport Way', 'Tamberías', '5401', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (97, '2085 Shasta Alley', 'Pampa de los Guanacos', '3181', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (70, '3468 Shasta Street', 'Carlos Casares', '6530', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (65, '086 Waubesa Hill', 'Rojas', '5246', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (67, '16 Bobwhite Circle', 'Concepción', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (56, '3 Mayer Hill', 'Corral', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (48, '101 Westridge Street', 'La Cumbre', '6354', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (24, '1 Hollow Ridge Alley', 'La Paloma', null, 'Uruguay');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (59, '771 Del Mar Plaza', 'Allen', '8328', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (84, '2 Onsgard Drive', 'Las Parejas', '2505', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (33, '3247 Melody Point', 'Neuquén', '8300', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (70, '98 Victoria Parkway', 'Corrientes', '3400', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (31, '4963 Jana Place', 'El Tabo', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (74, '32 Porter Drive', 'Yerba Buena', '4622', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (60, '0348 Crest Line Road', 'Avellaneda', '5212', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (21, '40480 Westridge Street', 'Bonpland', '3234', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (97, '1 Packers Alley', 'Lanús', '1870', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (12, '43 Fallview Avenue', 'Quilpué', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (40, '2 Corben Crossing', 'Bahía Blanca', '8000', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (23, '631 Autumn Leaf Park', 'Pehuajó', '6451', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (21, '00 Surrey Terrace', 'Pellegrini', '9017', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (12, '848 Banding Avenue', 'Chiguayante', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (93, '13577 Village Green Crossing', 'Unquillo', '5109', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (10, '3191 Meadow Ridge Circle', 'Del Campillo', '6271', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (8, '6402 Corben Center', 'Las Lajas', '5833', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (33, '891 Nelson Alley', 'Campana', '4111', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (49, '87 Leroy Place', 'Casilda', '2170', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (64, '348 Lighthouse Bay Circle', 'Aminga', '5301', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (3, '01 Dottie Terrace', 'Victoria', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (43, '69 Pennsylvania Crossing', 'Bernardo Larroudé', '6220', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (31, '90377 Fremont Street', 'Buenos Aires', '1871', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (94, '6 Messerschmidt Park', 'Cafayate', '4427', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (27, '2 Ridgeway Court', 'Sauce', null, 'Uruguay');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (13, '75 Tennessee Alley', 'Brinkmann', '2419', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (2, '77148 Duke Road', 'La Tigra', '5949', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (87, '56 Hermina Place', 'Pilcaniyeu', '8412', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (81, '0003 Gina Court', 'La Laja', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (94, '540 Dorton Hill', 'Mar del Plata', '7600', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (36, '6 Rigney Place', 'San Pedro', '4500', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (40, '8551 3rd Road', 'Villa Regina', '8336', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (85, '95985 Bartelt Alley', '28 de Noviembre', '9407', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (13, '38918 Colorado Junction', 'Puente Alto', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (95, '156 Kennedy Place', 'Río Segundo', '5972', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (29, '8885 Tennessee Plaza', 'Zárate', '3423', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (76, '7183 Nobel Point', 'Longaví', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (4, '8 Gulseth Place', 'San Roque', '4630', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (27, '98308 Texas Street', 'Capilla del Monte', '5184', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (33, '0344 Kensington Plaza', 'San Antonio', '4503', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (85, '16 Nancy Street', 'Pocito', '6430', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (100, '29963 Old Shore Hill', 'Morteros', '2421', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (98, '1 Derek Hill', 'Los Charrúas', '3212', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (9, '90443 Paget Circle', 'Yacimiento Río Turbio', '1649', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (16, '96 International Park', 'Santo Tomé', '5719', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (98, '5098 Morning Circle', 'Alta Gracia', '5186', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (26, '818 Porter Hill', 'Las Animas', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (17, '4 Acker Road', 'Young', null, 'Uruguay');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (32, '36290 East Trail', 'Espinillo', '3460', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (92, '8834 Cherokee Park', 'Villa Las Rosas', '5875', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (36, '5262 Farragut Crossing', 'San Antonio', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (95, '4183 Bashford Point', 'Comodoro Rivadavia', '9000', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (86, '60 New Castle Point', 'Río Pico', '9225', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (9, '15569 Corscot Place', 'Concordia', '3200', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (47, '807 Butternut Lane', 'Trinidad', null, 'Uruguay');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (75, '27928 Prairieview Alley', 'Charata', '3730', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (34, '44344 Comanche Junction', 'Limache', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (26, '08283 Graedel Crossing', 'El Tabo', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (9, '610 East Drive', 'Fraile Pintado', '4506', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (82, '3 Old Shore Trail', 'Termas de Río Hondo', '4221', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (39, '153 High Crossing Point', 'Presidencia Roque Sáenz Peña', '5444', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (10, '092 New Castle Pass', 'Ibarreta', '3624', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (44, '9316 School Plaza', 'Cruz del Eje', '5280', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (93, '6478 Grim Pass', 'Loreto', '3483', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (64, '54611 Lake View Court', 'Purranque', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (48, '575 Golf Course Trail', 'Carlos Tejedor', '6455', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (9, '754 Mitchell Place', 'Azul', '7300', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (83, '5 Pepper Wood Lane', 'San Francisco', '4655', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (28, '54 Tomscot Trail', 'Puerto Varas', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (14, '593 Aberg Pass', 'San Antonio', '4503', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (79, '4 Harbort Road', 'Los Cóndores', '5823', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (87, '85 Schlimgen Crossing', 'Rosario de Lerma', '4405', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (2, '8099 Killdeer Way', 'Rinconada', '4643', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (100, '061 Hudson Plaza', 'Zapala', '8340', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (40, '83 Del Mar Point', 'Camilo Aldao', '5285', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (67, '33 Calypso Junction', 'El Monte', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (38, '70 Forest Point', 'Vichadero', null, 'Uruguay');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (97, '54 Dryden Avenue', 'Chilecito', '3412', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (4, '0 Commercial Hill', 'Pehuajó', '6451', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (15, '4001 Gale Pass', 'Firmat', '2630', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (70, '73 Miller Way', 'Huinca Renancó', '6270', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (96, '652 Mesta Park', 'Presidencia Roque Sáenz Peña', '2124', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (40, '02301 Packers Park', 'Resistencia', '3500', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (31, '59468 Lotheville Way', 'Vicuña', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (52, '18 Meadow Ridge Parkway', 'Freire', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (74, '19610 Basil Avenue', 'Morteros', '2421', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (14, '2483 Eliot Avenue', 'Coronda', '2240', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (57, '31740 Gale Way', 'San Bautista', null, 'Uruguay');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (28, '9671 Redwing Junction', 'Azul', '7300', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (15, '98 Loftsgordon Trail', 'General José de San Martín', '3155', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (92, '0 Blaine Center', 'Pontevedra', '1761', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (39, '6 Roth Plaza', 'Los Frentones', '3712', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (95, '28 Lunder Street', 'Barranqueras', '3480', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (24, '4 Rockefeller Avenue', 'Gualeguay', '2840', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (15, '319 Manley Plaza', 'Tres Isletas', '4129', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (96, '97 West Street', 'El Bolsón', '8430', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (35, '4177 Lawn Avenue', 'Famaillá', '4132', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (35, '949 Southridge Crossing', 'Comallo', '8416', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (61, '8 Elmside Trail', 'Ezeiza', '1804', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (29, '4 Anniversary Pass', 'Federal', '3180', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (30, '32 Green Ridge Pass', 'Victoria', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (30, '93316 Garrison Court', 'Plottier', '8316', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (59, '3 Glendale Place', 'Avellaneda', '5212', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (99, '5843 Village Crossing', 'Viedma', '8500', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (47, '0 Shasta Terrace', 'Charras', '5807', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (100, '226 Warbler Trail', 'Nuevo Berlín', null, 'Uruguay');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (28, '8909 Veith Alley', 'Calilegua', '4514', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (63, '37 Thackeray Crossing', 'Rivadavia', '3081', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (28, '3 Jay Hill', 'Hernández', '3156', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (52, '1668 Red Cloud Avenue', 'Patquía', '2424', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (78, '98617 Fuller Point', 'Colonia Nicolich', null, 'Uruguay');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (100, '852 Sycamore Plaza', 'Villa La Angostura', '8407', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (44, '1531 Quincy Road', 'General Lavalle', '7103', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (48, '77 Starling Circle', 'Tres Isletas', '4129', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (52, '0 Lakewood Street', 'Isla Verde', '8146', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (13, '00104 Farragut Lane', 'Laguna Paiva', '3401', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (84, '4885 Bashford Hill', 'Santa Ana', '4631', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (28, '81 Hermina Circle', 'Río Segundo', '5972', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (19, '5 Miller Junction', 'Gobernador Gálvez', '2124', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (11, '7527 Pepper Wood Crossing', 'Posadas', '3300', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (71, '845 Mockingbird Avenue', 'Morón', '1765', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (60, '08 Sheridan Street', 'Nueva Helvecia', null, 'Uruguay');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (15, '9927 Banding Street', 'Ingenio La Esperanza', '4503', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (82, '34 Mayfield Junction', 'Palmitas', null, 'Uruguay');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (49, '8655 Utah Avenue', 'Loncoche', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (45, '7241 Dawn Alley', 'Bell Ville', '2550', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (15, '35229 Merrick Trail', 'General San Martín', '1702', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (18, '854 Blackbird Drive', 'Dolores', '7100', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (27, '9 Messerschmidt Parkway', 'Embarcación', '4550', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (23, '5 Dottie Terrace', 'Lo Prado', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (39, '5 Kings Circle', 'Esquina', '5131', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (9, '9 Fallview Circle', 'Diamante', '3105', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (13, '4817 Hallows Terrace', 'Castelli', '7114', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (83, '7 Sheridan Court', 'Lascano', null, 'Uruguay');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (97, '126 Charing Cross Lane', 'Barranqueras', '3480', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (13, '5 Arapahoe Pass', 'Neuquén', '8300', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (75, '1 Sherman Plaza', 'Pucón', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (60, '6 Larry Road', 'Villa General Belgrano', '5195', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (31, '15 Warrior Center', 'Puerto Montt', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (41, '73 Schlimgen Pass', 'Nueve de Julio', '3606', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (90, '06199 Hagan Court', 'Cipolletti', '8324', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (50, '58547 Reindahl Avenue', 'Aluminé', '8203', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (94, '0 Caliangt Parkway', 'Colegiales', '1871', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (91, '27221 Hintze Drive', 'Chivilcoy', '5571', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (91, '64206 Fremont Junction', 'Chicoana', '4423', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (18, '65122 Westport Point', 'Villa General Belgrano', '5195', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (70, '56077 3rd Crossing', 'Pirané', '3606', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (49, '32 Towne Plaza', 'Santiago Vázquez', null, 'Uruguay');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (34, '4908 Mendota Park', 'Delta del Tigre', null, 'Uruguay');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (14, '1104 Lakewood Gardens Trail', 'Unión', '2529', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (15, '7979 Pond Avenue', 'Fray Bentos', null, 'Uruguay');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (10, '077 Westerfield Circle', 'Puerto Rico', '3334', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (34, '34762 Larry Hill', 'Cachí', '4417', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (1, '6 2nd Way', 'Los Juríes', '3763', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (38, '52043 Dahle Circle', 'Bahía Blanca', '8000', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (52, '02012 4th Place', 'Río Ceballos', '5113', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (95, '858 Clyde Gallagher Court', 'Nueve de Julio', '3606', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (93, '4682 Hauk Point', 'Corralito', '5853', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (7, '14 Michigan Avenue', 'Arias', '2624', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (57, '13 Sutteridge Point', 'Quilino', '5214', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (30, '41244 Anderson Junction', 'Crespo', '3116', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (6, '8743 Clarendon Point', 'Fraile Pintado', '4506', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (19, '0 Farragut Pass', 'Vergara', null, 'Uruguay');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (91, '630 Novick Road', 'Cutral-Có', '8322', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (93, '25469 High Crossing Plaza', 'Cinco Saltos', '8303', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (40, '0435 Oak Crossing', 'Vera', '3550', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (62, '061 Forster Junction', 'Ancasti', '4701', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (32, '74 Butternut Place', 'General Levalle', '6132', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (52, '6 Mayer Court', 'Almafuerte', '3317', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (8, '8722 Forest Drive', 'Villa de Soto', '5284', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (17, '45 School Street', 'Mar del Plata', '7600', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (34, '43426 Scott Street', 'Pérez', '2121', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (96, '60347 Pine View Court', 'San José de Jáchal', '5461', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (10, '0085 Service Parkway', 'Pasco', '5925', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (87, '1 Transport Trail', 'Veinticinco de Mayo', '8201', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (4, '992 School Parkway', 'El Colorado', '4618', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (84, '262 Maywood Way', 'Arauco', '5311', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (1, '653 Forest Dale Parkway', 'Tamberías', '5401', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (44, '058 Huxley Crossing', 'Libertador General San Martín', '4514', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (68, '4 Lukken Parkway', 'Gálvez', '2253', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (7, '61317 Eastwood Trail', 'San Isidro de Lules', '4174', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (47, '14088 Maple Wood Trail', 'Belén de Escobar', '1625', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (97, '110 Kings Alley', 'Firmat', '2630', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (73, '95404 Farragut Trail', 'Nueve de Julio', '3606', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (82, '36 Atwood Lane', 'Santo Tomé', '5719', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (34, '75 Derek Center', 'Las Heras', '9017', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (62, '0496 Village Green Center', 'Maimará', '4624', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (47, '5 Rieder Park', 'Huillapima', '4726', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (48, '8 Ramsey Center', 'Coté-Lai', '3513', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (84, '675 Stuart Way', 'Frutillar', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (59, '8 Hauk Drive', 'Saladas', '3420', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (96, '3238 Fallview Lane', 'Luján de Cuyo', '5544', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (15, '23258 Anzinger Park', 'Остров Пасхи', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (72, '20797 Cascade Trail', 'Pergamino', '2700', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (17, '77 Comanche Hill', 'Brandsen', '1981', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (62, '5560 Nova Place', 'Villa Constitución', '2919', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (94, '4 Village Avenue', 'Apóstoles', '3358', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (96, '51 Waywood Street', 'Santa Ana', '4631', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (80, '07948 Badeau Plaza', 'El Cuy', '8333', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (75, '22422 Esker Park', 'Puerto Madryn', '9120', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (36, '557 Basil Drive', 'General Alvear', '3361', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (47, '11729 Sundown Hill', 'Libertador General San Martín', '5771', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (65, '86438 Mitchell Road', 'San Ramón de la Nueva Orán', '4530', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (97, '6141 4th Way', 'San Rafael', '5600', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (40, '96 Elmside Hill', 'Formosa', '3600', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (12, '53 Grim Center', 'Capioví', '3334', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (89, '8 Kropf Crossing', 'Villa Santa Rita', '4600', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (10, '96120 Twin Pines Hill', 'La Cocha', '4162', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (92, '57807 Corscot Parkway', 'Castillos', null, 'Uruguay');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (57, '934 Shasta Street', 'Santa Rosa', '4618', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (3, '43853 Acker Way', 'Médanos', '8134', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (74, '4 Beilfuss Circle', 'Villa Nueva', '5903', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (46, '416 Fair Oaks Crossing', 'Hernández', '3156', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (98, '44361 Center Center', 'El Tabo', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (89, '454 Hudson Street', 'Catriel', '8307', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (56, '8 Blaine Park', 'Trancas', '4124', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (61, '97452 Sachtjen Crossing', 'San Martín de los Andes', '8370', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (37, '625 Manufacturers Place', 'Capitán Bermúdez', '2156', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (52, '698 Marquette Road', 'Basail', '3516', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (41, '78692 Sachtjen Way', 'General Ramírez', '3165', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (24, '4 Spohn Plaza', 'Gualeguay', '2840', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (16, '8142 Corry Alley', 'Punta Alta', '8109', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (95, '8960 Everett Terrace', 'Luján de Cuyo', '5544', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (32, '81 Prairie Rose Parkway', 'Linares', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (92, '5301 Lukken Avenue', 'Almafuerte', '3317', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (10, '34 Westerfield Center', 'El Bolsón', '8430', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (62, '36850 Main Avenue', 'Buin', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (53, '81 Doe Crossing Court', 'Cinco Saltos', '8303', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (44, '56562 6th Park', 'Tinogasta', '5340', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (3, '1689 Hallows Trail', 'La Falda', '4640', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (73, '316 Fieldstone Court', 'General Martín Miguel de Güemes', '5383', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (29, '092 Northwestern Pass', 'Clodomira', '4338', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (94, '7997 Union Junction', 'Leones', '2594', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (61, '2 Prairie Rose Pass', 'Valcheta', '8536', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (39, '8759 Talmadge Court', 'Embalse', '5856', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (91, '7420 Gina Way', 'Paso de los Libres', '3230', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (50, '4 Fordem Avenue', 'Londres', '4753', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (97, '257 Tomscot Street', 'Trinidad', null, 'Uruguay');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (33, '55 Rockefeller Crossing', 'Saladas', '3420', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (61, '357 Debs Trail', 'Nueve de Julio', '3606', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (36, '79 Kipling Court', 'Mariano Moreno', '8357', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (14, '7 New Castle Center', 'Nueve de Julio', '3606', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (72, '38595 Almo Place', 'Caseros', '3262', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (29, '3673 Swallow Court', 'Traiguén', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (4, '1389 Kings Crossing', 'General Enrique Mosconi', '3636', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (11, '9451 Di Loreto Park', 'Pampa del Infierno', '3708', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (98, '6486 Badeau Lane', 'La Puerta de San José', '4751', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (51, '5580 Lunder Court', 'Pontevedra', '1761', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (6, '90370 Autumn Leaf Park', 'Plottier', '8316', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (14, '560 Vidon Park', 'San Carlos', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (77, '0735 Del Sol Point', 'Tecka', '9201', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (86, '499 Sullivan Circle', 'Morrison', '2568', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (15, '20539 Beilfuss Park', 'Garupá', '3304', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (31, '56438 Victoria Parkway', 'El Carmen', '3190', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (55, '53762 Riverside Terrace', 'General Belgrano', '7223', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (20, '503 Evergreen Crossing', 'Cañada de Gómez', '2500', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (53, '5561 Stephen Point', 'Morteros', '2421', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (83, '52 Prairie Rose Alley', 'San Javier', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (15, '90 Prairieview Plaza', 'Ingenio La Esperanza', '4503', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (72, '11 Hazelcrest Alley', 'Ibarreta', '3624', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (60, '80 Grover Way', 'Esperanza', '5131', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (2, '177 Barnett Terrace', 'Casilda', '2170', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (12, '45 Lunder Hill', 'La Falda', '4640', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (42, '0 Jenna Park', 'Río Tercero', '5850', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (30, '25518 Crest Line Junction', 'Temuco', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (80, '195 Cambridge Plaza', 'La Banda', '5249', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (39, '50181 Becker Plaza', 'Villa Allende', '5105', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (19, '4505 Hermina Park', 'Graneros', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (72, '3149 Spohn Center', 'Laprida', '4205', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (95, '38019 Laurel Circle', 'Esquina', '5131', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (38, '53 Amoth Hill', 'San Carlos de Bolívar', '6550', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (39, '9 Maywood Terrace', 'La Rioja', '5300', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (16, '59 Southridge Alley', 'Cañuelas', '1814', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (84, '1 Walton Circle', 'Palmitas', null, 'Uruguay');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (62, '53 Mifflin Point', 'Junín', '5281', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (27, '1 Towne Avenue', 'Guernica', '1862', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (86, '64 Union Point', 'Villa Ocampo', '3580', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (11, '26 Brown Pass', 'Traiguén', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (54, '1353 Rowland Pass', 'Calbuco', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (21, '251 Loomis Lane', 'Soriano', null, 'Uruguay');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (97, '2516 Forster Place', 'Huillapima', '4726', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (51, '91 Clemons Court', 'Morteros', '2421', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (30, '06 Anthes Trail', 'Castillos', null, 'Uruguay');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (88, '56 Thierer Lane', 'Pichilemu', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (59, '441 Hollow Ridge Point', 'Nueve de Julio', '3606', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (66, '2554 Del Sol Trail', 'La Ensenada', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (36, '157 Kings Parkway', 'Villa Carlos Paz', '5152', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (7, '6 Laurel Drive', 'Lampa', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (28, '91474 Burning Wood Circle', 'Villa La Angostura', '8407', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (34, '27 Bashford Court', 'San Antonio Oeste', '8520', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (50, '83 Corben Drive', 'Guatimozín', '2625', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (8, '712 New Castle Circle', 'San Carlos de Bolívar', '6550', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (77, '8 Merchant Avenue', 'General José de San Martín', '3155', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (27, '87 Karstens Street', 'Chilecito', '3412', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (56, '042 Hagan Junction', 'Durazno', null, 'Uruguay');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (84, '5 Nevada Hill', 'La Cocha', '4162', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (40, '280 Gulseth Drive', 'Añelo', '8305', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (85, '4 Gale Parkway', 'La Falda', '4640', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (78, '1231 Hansons Street', 'General Manuel J. Campos', '6309', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (60, '8 School Road', 'Santa Cruz', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (34, '1 Dixon Trail', 'Nueva Helvecia', null, 'Uruguay');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (85, '330 Starling Trail', 'Fray Bentos', null, 'Uruguay');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (45, '8208 Vernon Alley', 'Rada Tilly', '9001', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (62, '4 Schmedeman Trail', 'Londres', '4753', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (56, '681 Scoville Center', 'Las Lajas', '5833', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (48, '86485 Spaight Road', 'Sunchales', '2322', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (74, '66524 Hoffman Junction', 'Molina', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (19, '4 Jana Plaza', 'Mariscala', null, 'Uruguay');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (3, '574 Porter Pass', 'Villa del Rosario', '5963', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (86, '2 Thierer Circle', 'San Javier', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (22, '6186 Swallow Terrace', 'Caleufú', '6387', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (40, '7 Mcbride Plaza', 'Laguna Limpia', '3515', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (2, '3 Upham Pass', 'Corrientes', '3400', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (36, '44104 Bashford Hill', 'Monteros', '4142', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (21, '69730 Lake View Trail', 'Rojas', '5246', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (90, '59773 Veith Hill', 'Fray Bentos', null, 'Uruguay');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (86, '33159 Carberry Lane', 'Alejo Ledesma', '2662', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (56, '763 Carey Pass', 'Villa Mercedes', '5461', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (58, '00762 Manley Junction', 'Joaquín Suárez', null, 'Uruguay');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (81, '0008 Morrow Circle', 'La Ensenada', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (32, '6513 Clemons Crossing', 'Helvecia', '3003', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (5, '5709 Dottie Road', 'Quillota', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (61, '9906 Anhalt Pass', 'Piedra del Águila', '4624', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (77, '3 Starling Pass', 'Tafí Viejo', '4105', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (96, '1515 Summerview Street', 'Coronel Suárez', '7541', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (55, '17 Killdeer Parkway', 'Avellaneda', '5212', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (38, '33271 Ohio Alley', 'Mendoza', '5500', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (63, '961 Longview Point', 'Tomé', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (10, '8138 Lakewood Terrace', 'Mercedes', '3470', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (48, '2134 Elgar Point', 'Ovalle', null, 'Chile');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (73, '7 Red Cloud Alley', 'Tandil', '7000', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (7, '83 Corscot Pass', 'Centenario', '8309', 'Argentina');
insert into CustomerAddress (customer_id, address, city, postal_code, country) values (45, '1 Parkside Avenue', 'Villa Lugano', '5439', 'Argentina');
