insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Mercado Pago');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Debito');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
insert into PaymentMethod (method) values ('Credito');
insert into PaymentMethod (method) values ('Efectivo');
