INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Mercado Pago');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Debito');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
INSERT INTO PaymentMethod (method) VALUES ('Credito');
INSERT INTO PaymentMethod (method) VALUES ('Efectivo');
